=== getkey/bombhopperio-level/src/level.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "https://bombhopper.io/level.schema.json",
	"definitions": {
		"start_timing": {
			"type": "integer",
			"minimum": 0
		}
	},
	"title": "Level",
	"description": "A BombHopper.io level",
	"type": "object",
	"additionalProperties": false,
	"required": ["name", "timings", "entities"],
	"properties": {
		"name": {
			"type": "string",
			"description": "The level's name",
			"minLength": 1
		},
		"timings": {
			"type": "array",
			"items": [
				{
					"description": "2 stars",
					"$ref": "#/definitions/start_timing"
				},
				{
					"description": "3 stars",
					"$ref": "#/definitions/start_timing"
				}
			],
			"minItems": 2,
			"order": "desc",
			"additionalItems": false
		},
		"formatVersion": {
			"type": "integer",
			"description": "The version number of the schema the file corresponds to",
			"minimum": 0
		},
		"entities": {
			"type": "array",
			"items": {
				"$ref": "entity.schema.json#"
			}
		}
	}
}

=== getkey/bombhopperio-level/src/levelExamples/my_level.json
{
	"name": "My level",
	"timings": [
		0,
		0
	],
	"entities": [
		{
			"type": "text",
			"params": {
				"x": 500,
				"y": 300,
				"copy": {
					"en": "This is the default level!\nEdit it to your liking.",
					"fr": "Voici le niveau par défaut\nÉdite comme il te plait."
				},
				"anchor": {
					"x": 0.5,
					"y": 0.5
				}
			}
		},
		{
			"type": "normal",
			"params": {
				"vertices": [
					{
						"x": 720,
						"y": 600
					},
					{
						"x": 720,
						"y": 660
					},
					{
						"x": 840,
						"y": 660
					},
					{
						"x": 840,
						"y": 600
					}
				],
				"isStatic": true
			}
		},
		{
			"type": "ice",
			"params": {
				"vertices": [
					{
						"x": 60,
						"y": 360
					},
					{
						"x": 60,
						"y": 600
					},
					{
						"x": 720,
						"y": 600
					},
					{
						"x": 720,
						"y": 540
					},
					{
						"x": 480,
						"y": 540
					},
					{
						"x": 300,
						"y": 420
					},
					{
						"x": 180,
						"y": 420
					}
				],
				"isStatic": true
			}
		},
		{
			"type": "endpoint",
			"params": {
				"x": 900,
				"y": 360,
				"isStatic": true,
				"rightFacing": true,
				"angle": 0
			}
		},
		{
			"type": "player",
			"params": {
				"x": 240,
				"y": 400,
				"angle": 0,
				"isStatic": false,
				"magazine": [
					"grenade",
					"bullet"
				]
			}
		},
		{
			"type": "player",
			"params": {
				"x": 240,
				"y": 400,
				"angle": 0,
				"isStatic": false,
				"infiniteAmmo": "grenade"
			}
		},
		{
			"type": "normal",
			"params": {
				"vertices": [
					{
						"x": 60,
						"y": 240
					},
					{
						"x": 120,
						"y": 240
					},
					{
						"x": 120,
						"y": 300
					},
					{
						"x": 60,
						"y": 300
					}
				],
				"isStatic": false
			}
		}
	],
	"formatVersion": 0
}

=== getkey/bombhopperio-level/src/levelExamples/test_level_for_the_validator_tool.json
{
	"name": "test level for the validator tool",
	"timings": [
		123456789,
		1234567
	],
	"entities": [
		{
			"type": "normal",
			"params": {
				"vertices": [
					{
						"x": -300,
						"y": 600
					},
					{
						"x": -300,
						"y": 660
					},
					{
						"x": 1140,
						"y": 660
					},
					{
						"x": 1140,
						"y": 600
					}
				],
				"isStatic": true
			}
		},
		{
			"type": "paint",
			"params": {
				"vertices": [
					{
						"x": 840,
						"y": 510
					},
					{
						"x": 960,
						"y": 510
					},
					{
						"x": 960,
						"y": 540
					},
					{
						"x": 1050,
						"y": 480
					},
					{
						"x": 960,
						"y": 420
					},
					{
						"x": 960,
						"y": 450
					},
					{
						"x": 840,
						"y": 450
					}
				],
				"fillColor": 48896
			}
		},
		{
			"type": "endpoint",
			"params": {
				"x": 840,
				"y": 360,
				"isStatic": true,
				"rightFacing": true,
				"angle": -0.9424777960769379,
				"destination": "b3cd72ad-e47c-4aac-a720-3ea871d0330c"
			}
		},
		{
			"type": "player",
			"params": {
				"x": 240,
				"y": 400,
				"angle": -2.199114857512855,
				"isStatic": false,
				"magazine": [
					"grenade",
					"bullet",
					"empty",
					"bullet",
					"grenade",
					"bullet",
					"grenade",
					"bullet",
					"empty",
					"bullet",
					"empty",
					"bullet",
					"grenade",
					"bullet",
					"grenade"
				]
			}
		},
		{
			"type": "endpoint",
			"params": {
				"x": 1080,
				"y": 360,
				"isStatic": false,
				"rightFacing": true,
				"angle": 0
			}
		},
		{
			"type": "text",
			"params": {
				"x": 780,
				"y": 420,
				"copy": {
					"en": "static door"
				},
				"anchor": {
					"x": 0.5,
					"y": 0.5
				},
				"angle": 0.6457718232379019
			}
		},
		{
			"type": "text",
			"params": {
				"x": 1080,
				"y": 480,
				"copy": {
					"en": "non-static\ndoor"
				},
				"anchor": {
					"x": 0.5,
					"y": 0.5
				},
				"angle": 0
			}
		},
		{
			"type": "player",
			"params": {
				"x": 120,
				"y": 360,
				"angle": 0,
				"isStatic": true,
				"infiniteAmmo": "grenade"
			}
		},
		{
			"type": "text",
			"params": {
				"x": 120,
				"y": 300,
				"copy": {
					"en": "static"
				},
				"anchor": {
					"x": 0.5,
					"y": 0.5
				},
				"angle": 0
			}
		},
		{
			"type": "text",
			"params": {
				"x": 240,
				"y": 360,
				"copy": {
					"en": "non-static"
				},
				"anchor": {
					"x": 0.5,
					"y": 0.5
				},
				"angle": 0
			}
		},
		{
			"type": "normal",
			"params": {
				"vertices": [
					{
						"x": -300,
						"y": 480
					},
					{
						"x": -300,
						"y": 420
					},
					{
						"x": -240,
						"y": 420
					}
				],
				"isStatic": false
			}
		},
		{
			"type": "ice",
			"params": {
				"vertices": [
					{
						"x": -240,
						"y": 480
					},
					{
						"x": -120,
						"y": 420
					},
					{
						"x": -120,
						"y": 480
					},
					{
						"x": -180,
						"y": 540
					},
					{
						"x": -240,
						"y": 540
					},
					{
						"x": -180,
						"y": 480
					}
				],
				"isStatic": true
			}
		},
		{
			"type": "ice",
			"params": {
				"vertices": [
					{
						"x": -120,
						"y": 300
					},
					{
						"x": -60,
						"y": 300
					},
					{
						"x": -60,
						"y": 360
					},
					{
						"x": -180,
						"y": 360
					}
				],
				"isStatic": false
			}
		},
		{
			"type": "breakable",
			"params": {
				"vertices": [
					{
						"x": -60,
						"y": 480
					},
					{
						"x": 0,
						"y": 480
					},
					{
						"x": 0,
						"y": 600
					},
					{
						"x": -60,
						"y": 600
					}
				],
				"isStatic": true
			}
		},
		{
			"type": "breakable",
			"params": {
				"vertices": [
					{
						"x": 0,
						"y": 360
					},
					{
						"x": 60,
						"y": 360
					},
					{
						"x": 60,
						"y": 420
					}
				],
				"isStatic": false
			}
		},
		{
			"type": "deadly",
			"params": {
				"vertices": [
					{
						"x": 660,
						"y": 300
					},
					{
						"x": 660,
						"y": 540
					},
					{
						"x": 600,
						"y": 540
					}
				],
				"isStatic": false
			}
		},
		{
			"type": "deadly",
			"params": {
				"vertices": [
					{
						"x": 540,
						"y": 180
					},
					{
						"x": 600,
						"y": 180
					},
					{
						"x": 540,
						"y": 300
					},
					{
						"x": 600,
						"y": 420
					},
					{
						"x": 480,
						"y": 300
					},
					{
						"x": 360,
						"y": 300
					},
					{
						"x": 540,
						"y": 240
					},
					{
						"x": 480,
						"y": 180
					},
					{
						"x": 480,
						"y": 120
					}
				],
				"isStatic": true
			}
		},
		{
			"type": "bouncy",
			"params": {
				"vertices": [
					{
						"x": 180,
						"y": 480
					},
					{
						"x": 300,
						"y": 480
					},
					{
						"x": 300,
						"y": 600
					},
					{
						"x": 240,
						"y": 600
					}
				],
				"isStatic": true
			}
		},
		{
			"type": "bouncy",
			"params": {
				"vertices": [
					{
						"x": 420,
						"y": 360
					},
					{
						"x": 480,
						"y": 360
					},
					{
						"x": 480,
						"y": 420
					},
					{
						"x": 420,
						"y": 420
					}
				],
				"isStatic": true
			}
		},
		{
			"type": "bouncy",
			"params": {
				"x": 300,
				"y": 600,
				"radius": 15,
				"isStatic": true
			}
		},
		{
			"type": "ice",
			"params": {
				"x": 300,
				"y": 600,
				"radius": 15,
				"isStatic": true
			}
		},
		{
			"type": "breakable",
			"params": {
				"x": 300,
				"y": 600,
				"radius": 15,
				"isStatic": true
			}
		},
		{
			"type": "deadly",
			"params": {
				"x": 300,
				"y": 600,
				"radius": 15,
				"isStatic": true
			}
		},
		{
			"type": "normal",
			"params": {
				"x": 300,
				"y": 600,
				"radius": 14,
				"isStatic": true
			}
		},
		{
			"type": "player",
			"params": {
				"x": 720,
				"y": 540,
				"angle": 0,
				"isStatic": false,
				"magazine": []
			}
		}
	],
	"formatVersion": 0
}
